### ISSUE TITLE
Checklist: PZ формально не годится для подписания документов между агентами

### ISSUE THREAD

**Issue by JustAndrei** [JustAndrei/jdg-tools#17]
Profil Zaufany формально используется исключительно для подписания документов при обмене документами с гос. организациями, его нельзя использовать для подписания контракта с клиентом (см. https://www.biznes.gov.pl/pl/portal/0075#1). Для этого существует отдельный вид -- podpis kwalifikowany.
Список официальных провайдеров -- https://www.nccert.pl/
Покупка недешевая и не имеет большого смысла, если подписать надо лишь один контракт с клиентом. Но есть хорошее предложение -- одноразовая подпись за небольшую цену, см. https://www.elektronicznypodpis.pl/produkty/mobilnymszafir-do-jednorazowego-podpisu,300

**Comment by pointless-henry** [comment]
может ещё написать про **Forma Dokumentowa**?

[в чате есть отзыв](https://t.me/JDG_PBH/454361?thread=454258) о том, что Forma Dokumentowa (подпись SMS или обмен сканами по email) инспектор по ВНЖ принял без проблем. В тексте договора должен быть пункт, утверждающий, что эта форма применяется.
