### ISSUE TITLE
Checklist: заявление на объединение дел семьи

### ISSUE THREAD

**Issue by pointless-henry** [JustAndrei/jdg-tools#23]
Необязательная штука.
Может быть, для тех, кто подаётся семьёй, показывать в чеклисте документ "Prośba o połączenie spraw"? (т.е. когда выбран супруг или дети в выпадающих списках).

вопрос из чата: https://t.me/JDG_PBH/324549
ответ из чата: https://t.me/JDG_PBH/324561
(очень редкий вопрос: я нашёл только один в чате)

док:
[Prośba o połączenie spraw.docx](https://github.com/user-attachments/files/17754423/Prosba.o.polaczenie.spraw.docx)

**Comment by JustAndrei** [comment]
Какой-то не сильно существенный документ, в том плане, что
1. Наверняка он будет срабатывать только в определенных воеводствах, да еще и в зависимости от положения звёзд
2. В юридическом смысле он бесполезен, нет ни требований, ни оснований рассматривать связанные дела именно одним и тем же инспектором

**Comment by pointless-henry** [comment]
ok, согласен. можно и не добавлять.
