### ISSUE TITLE
Плохое качество скриншотов в Google Docs

### ISSUE THREAD

**Issue by pointless-henry** [JustAndrei/jdg-tools#33]
Вряд ли этот баг можно как-то исправить. Предлагаю просто в начале каждого документа писать предупреждение и рекомендацию открывать на ноутбуке или в официальном приложении Google Docs. Но ни в коем случае не в мобильном браузере.

Демо: скриншоты в мобильной web версии google docs (это инструменты разработчика, но так же выглядит в Chrome for Android)
![image](https://github.com/user-attachments/assets/17c1f2ed-94cc-421b-aaa6-85b3af51c2a9)

Демо: скриншоты в десктопной web версии google docs (Chrome for Windows)
![image](https://github.com/user-attachments/assets/b3acd9c6-e039-4b72-b820-d3f3fba3a196)

**Comment by JustAndrei** [comment]
Интересное. У меня установлено приложение Google Docs на Андроиде, оно автоматически перехватывает клик на ссылку и самостоятельно открывает документ в прекрасном виде, без этих проблем. Мне удалось воспроизвести проблему, открыв ссылку в Incognito, чтобы обойти приложение и посмотреть в браузере. Исходя из этого, могу лишь порекомендовать смотреть либо на компьютере, либо устанавливать Google Docs.
Я конечно могу пересохранить документ как PDF, что должно, наверное, решить проблему, но это вынудит постоянно держать две версии, рендер и исходник, чтобы иметь возможность вносить изменения при необходимости. Выглядит, пожалуй, избыточной заморочкой, т.к. в принципе проблема решаема на стороне пользователя.
Но я могу добавить в начале документа предупреждение.
