### ISSUE TITLE
Checklist: оригинал паспорта

### ISSUE THREAD

**Issue by pointless-henry** [JustAndrei/jdg-tools#7]
* [x] В строке "[Копия](https://justandrei.github.io/jdg-tools/checklist/#c-passport-copy) (сканы либо фото хорошего качества) всех [заполненных](https://justandrei.github.io/jdg-tools/checklist/#c-passport-pages) страниц паспорта" добавить уточнение, что нужно принести с собой "оригинал паспорта для сверки".

* [ ] А также после прочтения возникает вопрос: нужно ли при личной подаче документов иметь при себе старый паспорт для сверки?

**Comment by JustAndrei** [comment]
Про оригинал добавил в рамках изменений для #15 

> возникает вопрос: нужно ли при личной подаче документов иметь при себе старый паспорт для сверки?
Хороший вопрос. Не всегда старый паспорт имеется в наличии в принципе.
