### ISSUE TITLE
Checklist: копия паспорта Г в пакете документов С

### ISSUE THREAD

**Issue by pointless-henry** [JustAndrei/jdg-tools#8]
В строке "Копия (сканы либо фото хорошего качества) всех заполненных страниц паспорта" в столбце "С" вместо "+" должно быть значение "С Г".
Это рекомендация из чата от Ангелины: https://t.me/JDG_PBH/466765?thread=466764 + уточнение https://t.me/JDG_PBH/477962

демо предлагаемых изменений
![image](https://github.com/user-attachments/assets/6d79cd8b-3442-4859-bc5f-48fff627cb62)

**Comment by JustAndrei** [comment]
Не уверен в настоящей необходимости этого. Сам так не делал и не было вопросов, плюс Ангелина добавила же, что требования нет, просто рекомендация.

**Comment by pointless-henry** [comment]
OK, согласен. закрываю тикет.
